### PR TITLE
feat: sets up parallel builds

### PR DESCRIPTION
**Pull request by moltar**
This adds support for parallel builds.

Docs: https://docs.travis-ci.com/user/speeding-up-the-build/

I have not tested it beyond `travis lint`.

### CODE REVIEW

**Comment by moltar** [comment]
Seems to be working, judging by the logs: https://travis-ci.org/bsycorp/kind/jobs/512940741#L367

```
Setting environment variables from .travis.yml
$ export KUBERNETES_VERSION="v1.14.0"
$ export DOCKER_IMAGE_TAG="latest-1.14"
$ export MINIKUBE_VERSION="v1.0.0"
```

**Comment by moltar** [comment]
But got stuck on the password prompt for Docker, guessing because it is only available on master:

```
$ docker login -u $DOCKERUSER -p $DOCKERPASS
Password: 
```

Wonder why:

```yaml
branches:
  only:
  - master
```

Was ignored and why did the Travis build started anyways...

**Review by nhoughto — COMMENTED** [review]
How does this work? Is it a Travis specific thing? Looking at it looks like it redefines a variables 4 times 🤔

**Comment by moltar** [comment]
> How does this work? Is it a Travis specific thing?

Yup. I linked to the docs. It's called a "matrix".

You can see here that there are 4 jobs now running in parallel:

https://travis-ci.org/bsycorp/kind/builds/512940710

**Comment by moltar** [comment]
image

**Comment by moltar** [comment]
Please cancel this build, because it will never complete due to Docker login issue.

The only way to properly test it is on the `master` branch, because that is only where the Docker auth is probably whitelisted to be available.

**Comment by moltar** [comment]
Eh, just as I posted it errored out :)

**Comment by nhoughto** [comment]
Ah cool hack, will def fold that in when we fix 1.14 build 👍🏼
Will move docker login just before push and Seperate build vs push steps so PR builds work.

**Comment by moltar** [comment]
I think the last one should work.

Use this as a guide: https://docs.travis-ci.com/user/build-stages/matrix-expansion/

**Comment by moltar** [comment]
This last commit is not strictly necessary. But it keeps things clean. The push stages does not need those variables.

**Comment by moltar** [comment]
Wait, no, this is all wrong!

`DOCKER_IMAGE_TAG` IS needed on the push too argh

**Comment by moltar** [comment]
Meh, give up for today. Will look again on Monday.

Just to be clear - this PR is currently broken.

**Comment by nhoughto** [comment]
Captured the spirit of this change here:
https://github.com/bsycorp/kind/commit/860c9a95a48b629b5a6204c11a99b95d6522c21b

**Pull request closed without merging**
