### PR TITLE
+ dynamically login to a registry via docker-variables

### PR DESCRIPTION
**Pull request by strowi**
Hi,

nice work! Supplying registry-credentials at build-time might not be desirable. With this pr it's possible to do this via environment-variables.

regards,
Roman

### CODE REVIEW

**Review by nhoughto — APPROVED** [review]
Looks great! Thanks for the PR 👍🏼

**Comment by strowi** [comment]
sth. seems to be wrong with travis...

**Comment by nhoughto** [comment]
yeah i need to rejig the `docker push` into a travis deploy step so the build / deploy are executed differently, deploy only on tags or master smth

Your change is in master and pushed to docker hub tho, so should be nps :+1:

**Comment by strowi** [comment]
I saw, thx. Just haven't used travis before and was wondering..;)

**Pull request merged**
