### PR TITLE
Build and deploy kind image for Kubernetes version 1.23

### PR DESCRIPTION
**Pull request by itsnagaraj**

### CODE REVIEW

**Comment by itsnagaraj** [comment]
@nhoughto FYI

**Comment by nhoughto** [comment]
Have you tried this locally? it doesn't seem to work

**Comment by nhoughto** [comment]
hmm i think ive got a fix

**Comment by nhoughto** [comment]
pushed images and code separately

**Comment by itsnagaraj** [comment]
Thanks @nhoughto . I was able to build the image locally. Did you have to make changes outside the code to get this working?

**Comment by nhoughto** [comment]
Yep, I already pushed a commit to fix it and pushed a new image
You should be gtg

**Pull request closed without merging**
